<?php global $no_slides,$slide_show_visible; ?>
<?php $no_slides = 3;?>
<?php $slide_show_visible = false;?>
<?php
function color_array()
{
$colors = array(
 array('id' => 'ttr_designedbylink', 'std' => ''),
array('id' => 'ttr_designedby', 'std' => ''),
 array('id' => 'ttr_blockheading', 'std' => ''),
 array('id' => 'ttr_post_title_color', 'std' => ''),
 array('id' => 'ttr_post_title_hover_color', 'std' => '')
);
return $colors;
}
?>
<?php add_action( 'init', 'register_my_menus' );
function register_my_menus() {
register_nav_menus(
array(
'primary' => __('Menu',CURRENT_THEME)
)
);
}
function sidebar_options_array()
{
$sidebaroptions = array (
array(	"name" => __("Sidebar Options",CURRENT_THEME),
"type" => "title"),
array("type" => "open"),
array("name" => __("Block Heading Font Size",CURRENT_THEME),
"desc" =>"Enter the font size of Block Heading.",
"id" => "ttr_font_size_block",
"std" => "14",
"type" => "text"),
array("name" => __("Heading Tag for Block Heading",CURRENT_THEME),
"desc" =>"Choose heading tag for Block Heading.",
"id" => "ttr_heading_tag_block",
"std" => "h3",
"type" => "select",
"options" => array( "h1", "h2", "h3", "h4", "h5", "h6"),
),
array("type" => "close")
);
return $sidebaroptions;
}
function postcontent_array()
{
$postcontentoptions = array (
array(	"name" => __("PostContent Options",CURRENT_THEME),
"type" => "title"),
array("type" => "open"),
array("name" => __("Number of Featured Posts",CURRENT_THEME),
"desc" =>"How many posts would you like to be displayed as featured on the front page?",
"id" => "ttr_featured_post",
"std" => "1",
"type" => "text"),
array("name" => __("Number of Columns",CURRENT_THEME),
"desc" =>"In how many columns would you like to display the posts after featured posts on the front page?",
"id" => "ttr_post_layout",
"std" => "1",
"type"=> "text"),
array("name"=> __("Show Breadcrumbs On Page",CURRENT_THEME),
"desc" =>"Check this box if you would like to ENABLE the 'Breadcrumbs On Page'.",
"id" => "ttr_page_breadcrumb",
"std" => "true",
"type" => "checkbox"),
array("name"=> __("Show Breadcrumbs On Post",CURRENT_THEME),
"desc" =>"Check this box if you would like to ENABLE the 'Breadcrumbs On Post'.",
"id" => "ttr_post_breadcrumb",
"std" => "true",
"type" => "checkbox"),
array("name"=> __("Breadcrumbs Prefix",CURRENT_THEME),
"desc" =>"Choose breadcrumbs text.",
"id" => "ttr_breadcrumb_text",
"std" => "",
"type" => "text"),
array("name"=> __("Breadcrumbs Separator",CURRENT_THEME),
"desc" =>"Choose breadcrumbs text separator.",
"id" => "ttr_breadcrumb_text_separator",
"type" => "text",
"std" => "&raquo;",
"ex" => "&amp;raquo; for '&raquo;', &amp;rsaquo; for '&rsaquo;' and &amp;#47; for '&#47;'"),
array("name"=> __("Featured Image Width(in px.)",CURRENT_THEME),
"desc" =>"Enter width for featured image.",
"id" => "ttr_featured_image_width",
"type" => "text",
"std" => "100"),
array("name"=> __("Featured Image Height(in px.)",CURRENT_THEME),
"desc" =>"Enter height for featured image.",
"id" => "ttr_featured_image_height",
"type" => "text",
"std" => "100"),
array("name" => __("Search Results Per Page ",CURRENT_THEME),
"desc" =>"Enter the no of Posts for result.",
"id" => "ttr_query_result",
"std" => "5",
"type" => "text"),
array("type" => "close")
);
return $postcontentoptions;
}
function footer_options_array()
{
$copyright_url = home_url();
$facebook_url = '';
$linkedin_url = '';
$twitter_url = '';
$googleplus_url = '';
$footeroptions = array (
array(	"name" => __("Footer Options",CURRENT_THEME),
"type"=> "title"),
array("type" => "open"),
array("name" => __("Footer Designed By Font Size",CURRENT_THEME),
"desc" =>"Enter the font size of Footer Designed By.",
"id" => "ttr_font_size_designedby",
"std" => "20",
"type" => "text"),
array("name" => __("Footer Designed By Link Font Size",CURRENT_THEME),
"desc" =>"Enter the font size of Footer Designed By Link.",
"id" => "ttr_font_size_designedbylink",
"std"=> "14",
"type" => "text"),
array("type" => "close")
);
return $footeroptions;
}
function post_options_array()
{
$postoptions = array(
array("type" => "open"),
array( "name" => __("Display Post Title",CURRENT_THEME),
"desc" => "Check this box if you would like to DISABLE the Post Title",
"id"=> "ttr_post_title_checkbox",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Enable Post link",CURRENT_THEME),
"desc" => "Check this box if you would like to ENABLE the 'Post link'.",
"id"=> "ttr_post_link_enable_checkbox",
"type" => "checkbox",
"std" => "true"),
array("type" => "close")
);
return $postoptions;
}
function page_options_array()
{
$pageoptions = array(
array("type" => "open"),
array( "name" => __("Display Page Title",CURRENT_THEME),
"desc" => "Check this box if you would like to DISABLE the Page Title",
"id"=> "ttr_page_title_checkbox",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Header",CURRENT_THEME),
"desc" => "Check this box if you would like to DISABLE the Page Header",
"id"=> "ttr_page_head_checkbox",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Footer",CURRENT_THEME),
"desc" => "Check this box if you would like to DISABLE the Page Footer",
"id"=> "ttr_page_foot_checkbox",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Header Background Style",CURRENT_THEME),
"desc" => "Select Box for Header Image size",
"id"=> "ttr_header_size_select",
"type" => "select",
"std" => "none",
"options" => array(__("None",CURRENT_THEME), __("Fill",CURRENT_THEME), __("Horizontal Fill",CURRENT_THEME), __("Vertical Fill",CURRENT_THEME))),
array( "name" => __("Disable header Image Repeat",CURRENT_THEME),
"desc" => "Check this box if you dont want to repeat image",
"id"=> "ttr_background_repeat_enable_checkbox",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Header  Background Image",CURRENT_THEME),
"desc" => "Choose Header Image",
"id"=> "ttr_change_header_image_text",
"type" => "media",
"std" => ""),
array( "name" => __("Body Background Style",CURRENT_THEME),
"desc" => "Select Box for background Image size",
"id"=> "ttr_background_size_select",
"type" => "select",
"std" => "none",
"options" => array(__("None",CURRENT_THEME), __("Fill",CURRENT_THEME), __("Horizontal Fill",CURRENT_THEME), __("Vertical Fill",CURRENT_THEME))),
array( "name" => __("Disable background Image Repeat",CURRENT_THEME),
"desc" => "Check this box if you dont want to repeat image",
"id"=> "ttr_header_repeat_enable_checkbox",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Body Background Image",CURRENT_THEME),
"desc" => "Text Box for Body Background",
"id"=> "ttr_custom_style_text",
"type" => "media",
"std" => ""),
array("type" => "close")
);
return $pageoptions;
}
function general_options_array()
{
$generaloptions = array(
array("type" => "open"),
array( "name" => __("Google Analytics",CURRENT_THEME),
"desc" => "Text Box for google analytics",
"id"=> "ttr_google_analytics",
"type" => "textarea",
"std" => ""),
array( "name" => __("Enable Google Analytics",CURRENT_THEME),
"desc" => "Enable/Disable Google Analytics",
"id"=> "ttr_google_analytics_enable",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Custom CSS",CURRENT_THEME),
"desc" => "Text Box for custom css",
"id"=> "ttr_custom_style",
"type" => "textarea",
"std" => ""),
array( "name" => __("Display All Page Titles",CURRENT_THEME),
"desc" => "On/Off the page title",
"id"=> "ttr_all_page_title",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display All Post Titles",CURRENT_THEME),
"desc" => "On/Off the post title",
"id"=> "ttr_all_post_title",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Post Date",CURRENT_THEME),
"desc" => "On/Off the post date",
"id"=> "ttr_remove_date",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Author Name",CURRENT_THEME),
"desc" => "on/off the author name",
"id"=> "ttr_remove_author_name",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Show Post Category",CURRENT_THEME),
"desc" => "Show Post Category",
"id"=> "ttr_remove_post_category",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Navigation",CURRENT_THEME),
"desc" => "show/hide navigation",
"id"=> "ttr_post_navigation",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Older/Newer Posts Link",CURRENT_THEME),
"desc" => "Show/Hide Older/Newer Posts Link",
"id"=> "ttr_older_newer_posts",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Post Navigation",CURRENT_THEME),
"desc" => "Show/Hide post navigation",
"id"=> "ttr_post_navigation_post",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Previous/next Posts Link",CURRENT_THEME),
"desc" => "Show/Hide Previous/next  Posts Link",
"id"=> "ttr_previous_next_links",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Pagination Link Of Post Pages",CURRENT_THEME),
"desc" => "Show/Hide Pagination Link Of Post Pages",
"id"=> "ttr_pagination_link_posts",
"type" => "checkbox",
"std" => ""),
array( "name" => __("Display 'Comments are closed' Text",CURRENT_THEME),
"desc" => "Show/Hide 'Comments are closed' Text",
"id"=> "ttr_comments_closed_text",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Comments List",CURRENT_THEME),
"desc" => "Show/Hide Comments ",
"id"=> "ttr_comments_list",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Display Comments Form",CURRENT_THEME),
"desc" => "Show/Hide Comment form ",
"id"=> "ttr_comments_form",
"type" => "checkbox",
"std" => "true"),
array("name" => __("Show Comments list",CURRENT_THEME),
"desc" =>"Check this box to show comment form below comments list.",
"id" => "ttr_comment_list_form",
"std" => "Above Comment Form",
"type" => "radiobutton",
"options" => array("Above Comment Form", "Below Comment Form")),
array( "name" => __("Avatar Size",CURRENT_THEME),
"desc" => "Set Avatar size ",
"id"=> "ttr_avatar_size",
"type" => "text",
"std" => "75"),
array( "name" => __("Display Back To Top Button",CURRENT_THEME),
"desc" => "on/off the back to top button",
"id"=> "ttr_back_to_top",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Back To Top Icon",CURRENT_THEME),
"desc" => "Choose icon for Back To Top Button.",
"id"=> "ttr_icon_back_to_top",
"type" => "media",
"std" => ""),
array( "name" => __("Read More Text",CURRENT_THEME),
"desc" => "Change Text For Read More Link",
"id"=> "ttr_read_more",
"type" => "text",
"std" => __("Continue reading",CURRENT_THEME)),
array( "name" => __("Display Button For Read More",CURRENT_THEME),
"desc" => "on/off the Read More button",
"id"=> "ttr_read_more_button",
"type" => "checkbox",
"std" => __("true")),
array( "name" => __(" 'Read more' on all posts",CURRENT_THEME),
"desc" => "on/off the Read More on all posts",
"id"=> "ttr_post1_enable",
"type" => "checkbox",
"std" => __("true")),
array( "name" => __("Word Count",CURRENT_THEME),
"desc" => "After how many words you need read more",
"id"=> "ttr_read_length",
"type" => "text",
"std" => __("40")),
array( "name" => __("Display Search Icon In Search Widget",CURRENT_THEME),
"desc" => "Display/Hide Search Icon",
"id"=> "ttr_search_icon_enable",
"type" => "checkbox",
"std" => __("true")),
array("type" => "close")
);
return $generaloptions;
}
function error_options_array()
{
$error = array(
array("type" => "open"),
array( "name" => __("Heading",CURRENT_THEME),
"desc" => "Change Text For Error Message",
"id"=> "ttr_error_message_heading",
"type" => "textarea",
"std" => "This is somewhat embarrassing, isn&rsquo;t it?",CURRENT_THEME),
array( "name" => __("Content",CURRENT_THEME),
"desc" => "Change Text For Error Message",
"id"=> "ttr_error_message_content",
"type" => "textarea",
"std" => "It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.",CURRENT_THEME),
array( "name" => __("Enable Content",CURRENT_THEME),
"desc" => "Hide/Show Error Message Text",
"id"=> "ttr_error_message",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Enable Search",CURRENT_THEME),
"desc" => "Hide/Show Search Box",
"id"=> "ttr_error_search_box",
"type" => "checkbox",
"std" => "true"),
array( "name" => __("Content Image",CURRENT_THEME),
"desc" => "Choose Error Image",
"id"=> "ttr_error_image",
"type" => "media",
"std" => ""),
array( "name" => __("Enable Image In Content",CURRENT_THEME),
"desc" => "Hide/Show error image",
"id"=> "ttr_error_image_enable",
"type" => "checkbox",
"std" => ""),
array( "name" => __("Content Image Height",CURRENT_THEME),
"desc" => "Height Of The Error Image",
"id"=> "ttr_error_image_height",
"type" => "text",
"std" => "300"),
array( "name" => __("Content Image Width",CURRENT_THEME),
"desc" => "Width of The Error Image",
"id"=> "ttr_error_image_width",
"type" => "text",
"std" => "300"),
array( "name" => __("Redirect To Home Page(If Error Page Occurs)",CURRENT_THEME),
"desc" => "Redirect to Home Page While Error Occur",
"id"=> "ttr_error_home_redirect",
"type" => "checkbox",
"std" => ""),
array("type" => "close")
);
return $error;
}
function mm_options_array()
{
$mmoptions = array(
array("type" => "open"),
array( "name" => __("Enable Maintenance Mode",CURRENT_THEME),
"desc" => "Check this box if you would like to DISABLE the Page Title",
"id"=> "ttr_mm_enable",
"type" => "checkbox",
"std" => ""),
array( "name" => __("Title",CURRENT_THEME),
"desc" => "Title for Maintenance Mode page",
"id"=> "ttr_mm_title",
"type" => "text",
"std" => ""),
array( "name" => __("Content",CURRENT_THEME),
"desc" => "Contente for Maintenance Mode page",
"id"=> "ttr_mm_content",
"type" => "textarea",
"std" => ""),
array( "name" => __("Background Image",CURRENT_THEME),
"desc" => "Select Image for Maintenance Mode Page",
"id"=> "ttr_mm_image",
"type" => "media",
"std" => ""),
array("type" => "close")
);
return $mmoptions;
}
function googlemap_options_array()
{
$gmapoptions = array(
array("type" => "open"),
array( "name" => __("Type",CURRENT_THEME),
"desc" => "Choose Google Map type.",
"id"=> "ttr_googlemap_type",
"type" => "select",
"std" => "Road",
"options" => array(__("ROAD",CURRENT_THEME), __("SATELLITE",CURRENT_THEME), __("HYBRID",CURRENT_THEME), __("TERRAIN",CURRENT_THEME))),
array( "name" => __("Latitude",CURRENT_THEME),
"desc" => "Change Latitude of Map",
"id"=> "ttr_map_latitude",
"type" => "text",
"std" => "25.306944"),
array( "name" => __("Longitude",CURRENT_THEME),
"desc" => "Change Longitude of Map",
"id"=> "ttr_map_longitude",
"type" => "text",
"std" => "-257.858333"),
array( "name" => __("Width",CURRENT_THEME),
"desc" => "Change Width of Map",
"id"=> "ttr_map_width",
"type" => "text",
"std" => "400"),
array( "name" => __("Height",CURRENT_THEME),
"desc" => "Change Height of Map",
"id"=> "ttr_map_height",
"type" => "text",
"std" => "400"),
array( "name" => __("Display Marker",CURRENT_THEME),
"desc" => "Check this box if you would like to ENABLE the Position Marker.",
"id"=> "ttr_marker_enable",
"type" => "checkbox",
"std" => "true"),
array("type" => "close")
);
return $gmapoptions;
}
?>
